use_frameworks!

target 'SwiftBarcodeReader_Example' do
  pod 'SwiftBarcodeReader', :path => '../'

  target 'SwiftBarcodeReader_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
